# Generated by Django 4.2.1 on 2023-05-15 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense_type', models.CharField(max_length=260, unique=True, verbose_name='expense type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name_plural': 'Expense types',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expense', models.CharField(max_length=156, verbose_name='expense')),
                ('amount', models.FloatField(default=0.0, verbose_name='amount')),
                ('paid_to', models.CharField(max_length=100)),
                ('expense_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense.expensetype')),
            ],
            options={
                'verbose_name_plural': 'Expenses',
                'ordering': ('-id',),
            },
        ),
    ]
